### ISSUE TITLE
Missing layout files 

### ISSUE THREAD

**Issue by buttflattery** [akiraz2/yii2-blog#16]
**Describe the bug**
you are setting the layout path in the module like below 
![image](https://user-images.githubusercontent.com/1536454/104756252-66134700-577d-11eb-9ce5-e7b7340e6dad.png)

but there isnt any folder for the layouts in the modules source folder in the vendor directory

![image](https://user-images.githubusercontent.com/1536454/104756400-965ae580-577d-11eb-8ae5-b9bdc3f810b6.png)

**Comment by akiraz2** [comment]
Thanks! 
Did you already fix this issue? Can you provide PR?

**Comment by akiraz2** [comment]
temporarily removed
