### ISSUE TITLE
Incorrect Bootstrap Settings 

### ISSUE THREAD

**Issue by buttflattery** [akiraz2/yii2-blog#17]
**Describe the bug**
You have provided the `extra` tag to run the `akiraz/blog/bootstrap.php` which starts throwing exception if i am working on a feature branch that is yet to be merged into the master and i have to push a hotfix on live by creating a branch from master,

**To Reproduce**
Create a separate branch install the extension and configure it .
Then add & commit all your changes to that branch.
Try to create a new branch from `master` or `develop`, and switch to that branch.
Go to your site and refresh page.

**Expected behavior**
The application should work correctly, which isnt the case.

**Screenshots**
![image](https://user-images.githubusercontent.com/1536454/104896774-61c37580-5999-11eb-9808-1d957104bf16.png)

your defined settings will run the bootstrap file for all the applications, console, frontend, backend even API where its totally irrelevant

**Comment by akiraz2** [comment]
Did you add blog-module in /common/config/main.php? 
why `$this->getModule()` is non-object?

What is version of php?

P.S. develop branch is for version 2

**Comment by buttflattery** [comment]
@akiraz2 you are not getting the point that i am telling you, this has nothing to do with declaring the module in the `common/config/main.php` or anywhere else, i am talking about when you are developing a feature on a separate branch and everything is done on that branch including the installation of the module via composer, and the configurations.

After doing all of that if you switch back to you staging or develop branch where this extension isnt installed and neither the feature branch is merged , the above error is thrown, which does not make any sense.

PHP 7.2

**Comment by akiraz2** [comment]
After switching to staging branch (without module) - do you run `composer dumpautoload`?

**Comment by akiraz2** [comment]
So, if I remove `akiraz/blog/bootstrap.php` from `extra` - issue will be resolved?
ok, I will add information about bootstrap in config.php

**Comment by akiraz2** [comment]
removed extra section
docs are updated
