### ISSUE TITLE
Yii::setAlias @akiraz2 ?

### ISSUE THREAD

**Issue by akiraz2** [akiraz2/yii2-blog#2]
Если изменить путь к представлениям приложения (что конечно является обязательным условием использование модуля) через переопределение темы для представления. Необходимо в бутстрапе 
основного приложения добавить строчку:

Yii::setAlias('@akiraz2', dirname(dirname(__DIR__)) . '/vendor/akiraz2');

**Comment by chinabrother** [comment]
use @vendor/akiraz2

**Comment by akiraz2** [comment]
I hope Fixed!
I add alias to Bootstrap, and write about it in Readme.md
