### ISSUE TITLE
Not able to use blog migration

### ISSUE THREAD

**Issue by kavasey** [akiraz2/yii2-blog#3]
Hello @akiraz2 ,
Thanks for your blog module.
I get the following error when during installation

`c:\xampp\htdocs\yii2-core>yii migrate --migrationPath=@akiraz2/blog/migrations
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property 'redactorModule' of non-object'

in C:\xampp\htdocs\yii2-core\vendor\akiraz2\yii2-blog\Bootstrap.php:46

Stack trace:
#0 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Application.php(273): yii\console\Application->bootstrap()
#1 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\console\Application.php(124): yii\console\Application->init()
#2 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\console\Application->init()
#3 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Application.php(206): yii\console\Application->__construct()
#4 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\console\Application.php(89): yii\console\Application->__construct()
#5 C:\xampp\htdocs\yii2-core\yii(25): yii\console\Application->__construct()
#6 {main}`

**Comment by akiraz2** [comment]
Config common modules in common/config/main.php

```
    'modules' => [
        'blog' => [
            'class' => akiraz2\blog\Module::class,
            'urlManager' => '**urlManager**',// 'urlManager' by default, or maybe you can use own component urlManagerFrontend
            'imgFilePath' => '@frontend/web/img/blog/',
            'imgFileUrl' => '/img/blog/',                   
        ],
     ],    
```

**Comment by akiraz2** [comment]
also added alias
