### ISSUE TITLE
Не правильные имена таблиц

### ISSUE THREAD

**Issue by KakoitoTatar** [akiraz2/yii2-blog#6]
#7 Когда выплняется миграция, создаются таблицы с префиксом (если он есть), но в моделях эта особенность не учтена
Миграция:
` $this->createTable(
            '{{%blog_category}}'`
Модель:
`public static function tableName()
    {
        return 'blog_category';
    }`

**Comment by KakoitoTatar** [comment]
Не совместимо, нашёл еще баги

**Comment by KakoitoTatar** [comment]
В некоторых местах названия таблиц зашиты напрямую

**Comment by akiraz2** [comment]
#7 готово
