### ISSUE TITLE
Сохранение slug

### ISSUE THREAD

**Issue by nikdenly** [akiraz2/yii2-blog#9]
По умолчанию `slug `формируется простым копированием `title`
```
[
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                'slugAttribute' => 'slug'
],
```
Если в title есть латинские слова, то сохранятся только они.
Если title на русском, то ничего не сохраняется вообще. 
Нужна транслитерация.
Нашел два решения. Не проверял.
https://github.com/r3verser/yii2-SluggableBehavior 
https://habr.com/post/208328/

**Comment by akiraz2** [comment]
Принял. Протестю посмотрю

**Comment by ArtemKahramanov** [comment]
> По умолчанию `slug`формируется простым копированием `title`
> 
> ```
> [
>                 'class' => SluggableBehavior::class,
>                 'attribute' => 'title',
>                 'slugAttribute' => 'slug'
> ],
> ```
> Если в title есть латинские слова, то сохранятся только они.
> Если title на русском, то ничего не сохраняется вообще.
> Нужна транслитерация.
> Нашел два решения. Не проверял.
> https://github.com/r3verser/yii2-SluggableBehavior
> https://habr.com/post/208328/

Не смогли воспроизвести проблему, все сохраняется с транслитерацией, нужно больше информации

**Comment by nikdenly** [comment]
Пока что могу описать то, что наблюдаю у себя. 
1. Заголовок на русском = пустой slug
2. Заголовок на русско-английском (Hello мир) = hello
3. Заголовок на английском (Hello_world) = helloworld

Если повторить не получается, буду искать у себя.

**Comment by ArtemKahramanov** [comment]
Проверили с вашими данными, все в порядке, используется стандартный Slug behaviour
